# Generated by Django 2.2.12 on 2020-09-06 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketingpreference',
            old_name='mailchimp_msh',
            new_name='mailchimp_msg',
        ),
    ]
