# Generated by Django 2.2.12 on 2020-09-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_auto_20200907_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingpreference',
            name='mailchimp_msg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
