# Generated by Django 2.2.12 on 2020-09-10 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestemail',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='active',
        ),
    ]
